### PR TITLE
New pwm subsystem supporting centralized pwm resource coordination

### PR DESCRIPTION
**Pull request by rolandash**
**New features introduces by this new pwm subsystem:**

1. Real support of 8 main + 8 aux channels on a single FMU chip.
2. Global pwm resource manifest and allocation through board's timer_config.c. 
3. Centralized pwm resource (timers/channels) management and coordination. 
4. New model for all pwm devices. Added abstraction layer of PWM groups. Each pwm device is one or         more groups, other than previous pwm port based operations. FMU is one type of PWM devices.
5. Runtime, flexible pwm channels allocation thus pwm devices can use arbitrary idle channels, rather than hard coded on fixed channels.
6. Unified MindPX and new MindRacer hardware into one firmware target.
    MindPX: 8 Main + 8 AUX
    New MindRacer: 8 Main + 5 AUX

### CODE REVIEW

**Comment by rolandash** [comment]
**New PWM subsystem design**

new_pwm_design
)

**Comment by rolandash** [comment]
**PwmGroups base class**
PwmGroups is the base class for all pwm devices in the system, derived from CDev.
PwmGroups maintains the global map of all allocated pwm timers and channels, and detects conflicts between different pwm device usage.

**Static PWM devices**
Derived from PwmGroups.
FMU, ECU, fixed rgb pwm led, are all static pwm devices. These devices have fixed hardware pwm pins wiring, and timers/channels needed are predefined in board config file, and can not be changed during run time.

**Floating PWM devices**
Derived from PwmGroups.
These devices can be connected to any free pwm channels to work, as their working channels can be defined during runtime, through UI (GCS).
For example, camera trigger previously were assigned to working on AUX channels. In this new pwm subsystem, camera trigger is a floating pwm device. It can also be connected to free Main channels, as long as pwm rate matching.
This flexibility improves the efficiency of pwm channel usage greatly, as on some airframes when aux channels are occupied, then if still free channels on Main available then camera trigger can still be used.

PWM heaters, or external PWM LEDs, can all be driven as floating type devices like this way.

**ECU (Engine Control Unit)**
ECU is a component newly introduced, to resolve the problem that support both Main and AUX channels simultaneously in a single flight control chip. The concept of ECU is bit different from FMU(traditionally), as ECU has no intention to manage like RC inputs or safety button, but rather a simple direct PWM channel drive component. 
When ECU is presented and enabled, it will drive Main channels, and left AUX channels handled by FMU.

**Comment by rolandash** [comment]
The document in this PR is a resort of the content in previous PR [#2](https://github.com/airmind/OpenMindPX/pull/2)

**Comment by davids5** [comment]
Starting points:

1. "FMU Breakup" 
Safety: https://github.com/PX4/Firmware/pull/10119
Multi Module:https://github.com/PX4/Firmware/tree/pr-module_base_multi 

2. Document the io_timer hierarchy
 Trigger 
Capture
Servo

3. Make times configs instance -able (runtime not compile time)

**Pull request merged**
